workspace:
  base: /drone
  path: src

branches:
  - master

clone:
  git:
    image: plugins/git:next
    pull: true

pipeline:
  cache-restore:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    restore: true
    when:
      local: false

  frontend-deps:
    image: webhippie/nodejs:latest
    pull: true
    commands:
      - yarn install

  frontend-lint:
    image: webhippie/nodejs:latest
    pull: true
    commands:
      - gulp lint

  frontend-build:
    image: webhippie/nodejs:latest
    pull: true
    commands:
      - gulp pack

  cache-rebuild:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    rebuild: true
    mount:
      - node_modules
    when:
      local: false
      event: [ push ]

  cache-flush:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    flush: true
    flush_age: 14
    when:
      local: false
      event: [ push ]

  upload-artifact:
    image: plugins/s3:1
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    bucket: documentation
    endpoint: https://minio.owncloud.com
    path_style: true
    strip_prefix: build/
    source: build/ui-bundle.zip
    target: /
    when:
      local: false
      event: [ push ]

  github-release:
    image: plugins/github-release:1
    pull: true
    secrets: [ github_token ]
    files:
      - build/ui-bundle.zip
    when:
      local: false
      event: [ tag ]

  notify-slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: documentation
    when:
      local: false
      event: [ push, tag ]
      status: [ success, failure ]
